version: '3.3'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3333:3333'
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: realestate
    volumes:
      - ./:/app
      - /app/api/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mvertes/alpine-mongo
    container_name: mongo
    ports:
      - '27019:27017'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
